version: '3.8'
services:
  suscriber:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: flask --debug run
    expose:
      - 5000
    volumes:
      - home_data:/home/app
    env_file:
      - ./.env.suscriber.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data_prod:
  home_data: